import os
import pathlib
import shlex
import sys

_SEEDED_MARKER = "# Generated by `pre-commit --install`. Do not edit."


def _seeded_hook(target: str, env: dict[str, str]) -> str:
    """A hook script that defaults some variables, then execs the wrapper.

    Defaults rather than overrides: `${VAR:-value}` leaves alone a value the
    caller already exported, so CI can still point the wrapper elsewhere.
    """
    lines = ["#!/bin/bash --norc", _SEEDED_MARKER, "set -euo pipefail"]
    for name, value in env.items():
        if not name or "=" in name:
            raise ValueError(f"not a usable environment variable name: {name!r}")
        lines.append(f'export {name}="${{{name}:-{value}}}"')
    lines.append(f'exec "$(dirname "$0")/{target}" "$@"')
    return "\n".join(lines) + "\n"


def install_hook(
    repo_root: pathlib.Path,
    *,
    force: bool = False,
    env: dict[str, str] | None = None,
) -> int:
    """Point git's pre-commit hook at `bin/pre-commit`.

    With no `env` the hook is a relative symlink. With `env` it is a small
    generated script that seeds those variables first -- for a repo whose wrapper
    needs one set, where relying on the developer to export it before every
    commit would fail quietly and often.
    """
    hook_wrapper = repo_root / "bin" / "pre-commit"
    git_hook_path = repo_root / ".git" / "hooks" / "pre-commit"

    if not hook_wrapper.exists():
        print(f"Hook wrapper not found at {hook_wrapper}", file=sys.stderr)
        return 1

    hooks_dir = git_hook_path.parent
    if not hooks_dir.is_dir():
        print(f"Git hooks dir not found at {hooks_dir}", file=sys.stderr)
        return 1

    target = os.path.relpath(hook_wrapper, start=hooks_dir)
    # Build (and so validate) the replacement before disturbing what is there.
    replacement = _seeded_hook(target, env) if env else None

    if git_hook_path.is_symlink():
        current = os.readlink(git_hook_path)
        if replacement is None and current == target:
            print(f"Already installed: {git_hook_path} -> {target}")
            return 0
        if current != target and not force:
            print(
                f"Refusing to overwrite existing hook at {git_hook_path} "
                f"(symlink -> {current}); pass --force to replace",
                file=sys.stderr,
            )
            return 1
        git_hook_path.unlink()
    elif git_hook_path.exists():
        existing = git_hook_path.read_text(errors="replace")
        ours = _SEEDED_MARKER in existing
        if ours and replacement == existing:
            print(f"Already installed: {git_hook_path}")
            return 0
        if not ours and not force:
            print(
                f"Refusing to overwrite existing hook at {git_hook_path}; "
                f"pass --force to replace",
                file=sys.stderr,
            )
            return 1
        git_hook_path.unlink()

    if replacement is None:
        git_hook_path.symlink_to(target)
        print(f"Installed: {git_hook_path} -> {target}")
        return 0

    git_hook_path.write_text(replacement)
    git_hook_path.chmod(0o755)
    seeded = " ".join(f"{k}={shlex.quote(v)}" for k, v in env.items())
    print(f"Installed: {git_hook_path} -> {target} (seeding {seeded})")
    return 0
