"""The generated companion to `toolshed.toml`: one size + digest per platform.

Digests live apart from the manifest so that bumping a version stays a one-line
hand edit and the machine-generated half can be regenerated and reviewed as a
unit. `render pin` writes this file; nothing else should.
"""

import pathlib
import tomllib
from dataclasses import dataclass

from toolshed.manifest import PLATFORMS, ManifestError

LOCK_HEADER = "# Generated by `render pin` from toolshed.toml. Do not edit.\n"


@dataclass(frozen=True)
class PlatformPin:
    size: int
    digest: str


class Lock:
    """Pinned asset identities, keyed by tool name then platform."""

    def __init__(self, pins: dict[str, dict[str, PlatformPin]]) -> None:
        self._pins = pins

    def get(self, tool_name: str, platform: str) -> PlatformPin | None:
        return self._pins.get(tool_name, {}).get(platform)

    def missing_platforms(self, tool_name: str) -> list[str]:
        """Target platforms this tool has no pin for."""
        pinned = self._pins.get(tool_name, {})
        return [p for p in PLATFORMS if p not in pinned]

    def is_pinned(self, tool_name: str) -> bool:
        return not self.missing_platforms(tool_name)

    def with_pin(self, tool_name: str, platform: str, pin: PlatformPin) -> "Lock":
        pins = {name: dict(entries) for name, entries in self._pins.items()}
        pins.setdefault(tool_name, {})[platform] = pin
        return Lock(pins)

    def restricted_to(self, tool_names: set[str]) -> "Lock":
        """Drop pins for tools the manifest no longer declares."""
        return Lock(
            {
                name: entries
                for name, entries in self._pins.items()
                if name in tool_names
            }
        )

    def dumps(self) -> str:
        lines = [LOCK_HEADER]
        for tool_name in sorted(self._pins):
            for platform in PLATFORMS:
                pin = self._pins[tool_name].get(platform)
                if pin is None:
                    continue
                lines.append(f'\n[tool."{tool_name}"."{platform}"]\n')
                lines.append(f'digest = "{pin.digest}"\n')
                lines.append(f"size = {pin.size}\n")
        return "".join(lines)


def parse_lock(text: str) -> Lock:
    data = tomllib.loads(text)
    pins: dict[str, dict[str, PlatformPin]] = {}
    for tool_name, platforms in data.get("tool", {}).items():
        for platform, entry in platforms.items():
            if platform not in PLATFORMS:
                raise ManifestError(
                    f"lock entry '{tool_name}': unknown platform '{platform}'"
                )
            try:
                pins.setdefault(tool_name, {})[platform] = PlatformPin(
                    size=int(entry["size"]), digest=str(entry["digest"])
                )
            except KeyError as e:
                raise ManifestError(
                    f"lock entry '{tool_name}.{platform}': missing {e}"
                ) from e
    return Lock(pins)


def load_lock(path: pathlib.Path) -> Lock:
    if not path.exists():
        return Lock({})
    try:
        return parse_lock(path.read_text())
    except tomllib.TOMLDecodeError as e:
        raise ManifestError(f"{path}: {e}") from e
